name: eiva
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^10.2.0
  flutter_bloc: ^8.1.3
  bloc_test: ^9.1.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  cupertino_icons: ^1.0.2
  get_it: ^7.6.4
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^5.0.0
  cloud_firestore: ^4.11.0
  firebase_core: ^2.19.0
  firebase_storage: ^11.3.1
  firebase_auth: ^4.11.1
  firebase_messaging: ^14.7.1
  firebase_crashlytics: ^3.4.1
  firebase_analytics: ^10.6.1
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.5.0
  shared_preferences: ^2.2.2
  lottie: ^2.7.0
  intl: any
  flutter_localization: ^0.1.14
  phone_form_field: ^8.1.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/imgs/
    

  fonts:
    - family: Gilory
      fonts:
        - asset: assets/font/Gilroy/Gilroy-Black.ttf
        - asset: assets/font/Gilroy/Gilroy-Bold.ttf
   
